import React, { useState, useRef } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, RefreshCw, Image as ImageIcon, AlertCircle } from "lucide-react";
import { useImageGeneration } from '@/app/hooks/useImageGeneration';
import { useAIImageGeneration } from '@/app/hooks/useAIImageGeneration';
import { KidDetails, PageType } from '@/models';

export interface ImageGenerationComponentProps {
  userId: string;
  kidDetails: KidDetails;
  prompt: string;
  pageType?: PageType;
  outputCount?: number;
  storyId: string;
  parameters?: {
    size?: string;
    style?: string;
  };
  updatePath?: string; // Add updatePath parameter
  pageText?: string; // Page text for combined generation
  pageNum?: number; // Page number for combined generation
  useCombinedGeneration?: boolean; // Flag to use the new combined function
  onSuccess?: (images: string[]) => void;
  onError?: (error: string) => void;
  onGenerationStart?: () => void;
  showToast?: boolean;
  className?: string;
  title?: string;
  description?: string;
  buttonText?: string;
  buttonVariant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
  disabled?: boolean;
  autoGenerate?: boolean;
  showGeneratedImages?: boolean;
  onImageSelect?: (imageUrl: string) => void;
  selectedImageUrl?: string;
  useAIBots?: boolean;
  onClose?: () => void; // Callback to close the generator
  isGeneratingImage?: boolean; // Track if image is currently generating
  hideCardWrapper?: boolean; // Hide the card wrapper for cleaner UI
  environment?: 'development' | 'production'; // Environment for Firestore paths
}

export const ImageGenerationComponent: React.FC<ImageGenerationComponentProps> = ({
  userId,
  kidDetails,
  prompt,
  pageType,
  outputCount = 1,
  storyId,
  parameters,
  updatePath,
  pageText,
  pageNum,
  useCombinedGeneration = false,
  onSuccess,
  onError,
  onGenerationStart,
  showToast = true,
  className = "",
  title = "Generate Image",
  description,
  buttonText = "Generate Image",
  buttonVariant = "default",
  disabled = false,
  autoGenerate = false,
  showGeneratedImages = true,
  onImageSelect,
  selectedImageUrl,
  useAIBots = false,
  onClose,
  isGeneratingImage: externalIsGenerating,
  hideCardWrapper = false,
  environment = 'development'
}) => {
  console.log('[ImageGenerationComponent] Rendered with props:', {
    userId,
    kidId: kidDetails?.id,
    storyId, // Add storyId to debug log
    hasPrompt: !!prompt,
    promptPreview: prompt?.substring(0, 50) + '...',
    pageType,
    disabled,
    autoGenerate,
    useAIBots
  });

  const [generatedImages, setGeneratedImages] = useState<string[]>([]);
  const [localSelectedImage, setLocalSelectedImage] = useState<string | null>(selectedImageUrl || null);
  const hasAutoGeneratedRef = useRef(false);

  // Use the appropriate hook based on the useAIBots flag
  const legacyHook = useImageGeneration({
    userId,
    kidDetails,
    storyId,
    showToast,
    environment,
    onSuccess: (images) => {
      console.log('[ImageGenerationComponent] Legacy hook success callback', images);
      setGeneratedImages(images);
      onSuccess?.(images);
    },
    onError: (error) => {
      console.error('[ImageGenerationComponent] Legacy hook error callback', error);
      onError?.(error);
    }
  });

  const aiHook = useAIImageGeneration({
    userId,
    kidDetails,
    storyId,
    showToast,
    useAIBots: true,
    useCombinedGeneration,
    pageText,
    pageNum,
    environment,
    onSuccess: (images) => {
      console.log('[ImageGenerationComponent] AI hook success callback', images);
      setGeneratedImages(images);
      onSuccess?.(images);
    },
    onError: (error) => {
      console.error('[ImageGenerationComponent] AI hook error callback', error);
      onError?.(error);
    }
  });

  const { generateImage, isGenerating, error, clearError } = useAIBots ? aiHook : legacyHook;

  console.log('[ImageGenerationComponent] Hook state:', {
    useAIBots,
    isGenerating,
    hasError: !!error,
    hasGenerateFunction: !!generateImage
  });

  const handleGenerate = React.useCallback(async () => {
    console.log('[ImageGenerationComponent] handleGenerate called', {
      prompt,
      pageType,
      outputCount,
      userId,
      kidId: kidDetails.id,
      isGenerating,
      disabled,
      useCombinedGeneration,
      hasPageText: !!pageText
    });

    // Prevent duplicate calls if already generating
    if (isGenerating) {
      console.log('[ImageGenerationComponent] Already generating, skipping duplicate call');
      return;
    }

    // For combined generation with pageText, we don't need a prompt (AI will generate it)
    // For traditional generation, we need a prompt
    if (!useCombinedGeneration && !prompt) {
      console.error('[ImageGenerationComponent] No prompt provided for traditional generation, cannot generate image');
      return;
    }

    if (useCombinedGeneration && !pageText) {
      console.error('[ImageGenerationComponent] No pageText provided for combined generation, cannot generate image');
      return;
    }

    clearError();
    
    // Notify parent that generation is starting
    console.log('[ImageGenerationComponent] Calling onGenerationStart callback');
    onGenerationStart?.();
    
    console.log('[ImageGenerationComponent] Starting image generation...', {
      storyId,
      useCombinedGeneration,
      hasPrompt: !!prompt,
      hasPageText: !!pageText
    });
    
    const result = await generateImage({
      prompt,
      pageType,
      outputCount,
      storyId,
      updatePath, // Pass updatePath if provided
      parameters: {
        model: 'dall-e-3',
        quality: 'hd',
        style: 'vivid',
        size: '1024x1024',
        ...parameters
      }
    });

    console.log('[ImageGenerationComponent] Generation result:', result);

    if (result.success && result.data) {
      console.log('[ImageGenerationComponent] Successfully generated images:', result.data);
      setGeneratedImages(result.data);
      // Auto-select first image if only one generated
      if (result.data.length === 1 && !localSelectedImage) {
        setLocalSelectedImage(result.data[0]);
        onImageSelect?.(result.data[0]);
      }
    } else {
      console.error('[ImageGenerationComponent] Generation failed:', result.error);
    }
  }, [clearError, generateImage, prompt, pageType, outputCount, parameters, localSelectedImage, onImageSelect, isGenerating, onGenerationStart, storyId, useCombinedGeneration, pageText, updatePath]);

  const handleImageSelect = React.useCallback((imageUrl: string) => {
    setLocalSelectedImage(imageUrl);
    onImageSelect?.(imageUrl);
  }, [onImageSelect]);

  const handleRetry = React.useCallback(() => {
    handleGenerate();
  }, [handleGenerate]);

  // Auto-generate on mount if enabled
  React.useEffect(() => {
    // For combined generation, check for pageText; for traditional, check for prompt
    const hasRequiredData = useCombinedGeneration ? !!pageText : !!prompt;
    
    // Prevent duplicate auto-generation (React StrictMode causes effects to run twice)
    if (autoGenerate && hasRequiredData && !isGenerating && generatedImages.length === 0 && !hasAutoGeneratedRef.current) {
      console.log('[ImageGenerationComponent] Auto-generate triggered');
      hasAutoGeneratedRef.current = true;
      handleGenerate();
    }
    // Only run on mount or when autoGenerate/prompt/pageText changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, prompt, pageText, useCombinedGeneration]);

  const content = (
    <div className="space-y-4">
        {/* Error Display */}
        {error && (
          <div className="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded-md">
            <AlertCircle className="h-4 w-4 text-red-600 flex-shrink-0" />
            <span className="text-red-700 text-sm flex-1">{error}</span>
            <Button
              variant="outline"
              size="sm"
              onClick={handleRetry}
              disabled={isGenerating}
              className="ml-2 border-red-300 text-red-700 hover:bg-red-100"
            >
              <RefreshCw className="h-3 w-3 mr-1" />
              Retry
            </Button>
          </div>
        )}

        {/* Generate Button */}
        {!autoGenerate && (
          <div className="space-y-2">
            <Button
              onClick={() => {
                console.log('[ImageGenerationComponent] Button clicked', {
                  disabled,
                  isGenerating,
                  hasPrompt: !!prompt,
                  hasPageText: !!pageText,
                  useCombinedGeneration
                });
                handleGenerate();
              }}
              disabled={disabled || isGenerating || (!useCombinedGeneration && !prompt) || (useCombinedGeneration && !pageText)}
              variant={buttonVariant}
              className="w-full"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <ImageIcon className="mr-2 h-4 w-4" />
                  {buttonText}
                </>
              )}
            </Button>
          </div>
        )}

        {/* Loading State */}
        {isGenerating && (
          <div className="flex items-center justify-center py-8">
            <div className="text-center space-y-2">
              <Loader2 className="h-8 w-8 animate-spin mx-auto" />
              <p className="text-sm text-muted-foreground">Generating your image...</p>
            </div>
          </div>
        )}

        {/* Generated Images */}
        {showGeneratedImages && generatedImages.length > 0 && !isGenerating && (
          <div className="space-y-4">
            <h4 className="text-sm font-medium">Generated Images:</h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {generatedImages.map((imageUrl, index) => (
                <div
                  key={index}
                  className={`relative cursor-pointer rounded-lg overflow-hidden border-2 transition-all ${
                    localSelectedImage === imageUrl
                      ? 'border-primary ring-2 ring-primary/20'
                      : 'border-border hover:border-primary/50'
                  }`}
                  onClick={() => handleImageSelect(imageUrl)}
                >
                  <img
                    src={imageUrl}
                    alt={`Generated image ${index + 1}`}
                    className="w-full h-32 object-cover"
                    loading="lazy"
                  />
                  {localSelectedImage === imageUrl && (
                    <div className="absolute inset-0 bg-primary/10 flex items-center justify-center">
                      <div className="bg-primary text-primary-foreground rounded-full p-1">
                        <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* No Images State */}
        {!isGenerating && generatedImages.length === 0 && !error && (
          <div className="text-center py-8 text-muted-foreground">
            <ImageIcon className="h-12 w-12 mx-auto mb-2 opacity-50" />
            <p className="text-sm">No images generated yet</p>
            {!autoGenerate && (
              <p className="text-xs mt-1">Click the generate button to create images</p>
            )}
          </div>
        )}
    </div>
  );

  if (hideCardWrapper) {
    return (
      <div className={className}>
        {onClose && (
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-sm font-medium">{title}</h4>
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              disabled={isGenerating || externalIsGenerating}
              className="h-8 w-8 p-0"
              title={isGenerating || externalIsGenerating ? "Generation in progress..." : "Close"}
            >
              ×
            </Button>
          </div>
        )}
        {content}
      </div>
    );
  }

  return (
    <Card className={`w-full ${className}`}>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <ImageIcon className="h-5 w-5" />
          {title}
        </CardTitle>
        {description && (
          <p className="text-sm text-muted-foreground">{description}</p>
        )}
      </CardHeader>
      
      <CardContent>
        {content}
      </CardContent>
    </Card>
  );
};

export default ImageGenerationComponent;
