import { NextRequest, NextResponse } from "next/server";
import { OpenAIClient } from "@/app/network/ai-bots/OpenAIClient";
import { ResponseHandler } from "@/app/network/ai-bots/ResponseHandler";
import { BOTS_IDS, getBotVersion } from "@/app/network/ai-bots";

export async function POST(request: NextRequest) {
  const { prompt, referenceImageUrl, additionalParams } = await request.json();
  
  console.log("=== STORY IMAGE API REQUEST ===");
  console.log("Request body:", { prompt, referenceImageUrl, additionalParams });
  console.log("Prompt value:", prompt);
  console.log("ReferenceImageUrl value:", referenceImageUrl);
  
  if (!prompt && !referenceImageUrl) {
    return NextResponse.json(
      ResponseHandler.error("Either a prompt or reference image is required"),
      { status: 400 }
    );
  }

  return ResponseHandler.wrap(async () => {
    // Get bot version from Remote Config
    const botVersion = await getBotVersion('STORY_IMAGE_AI');
    let imageUrl: string;
    
    if (referenceImageUrl) {
      // Use the AI bot with reference image
      const promptToUse = prompt || "create";
      console.log("Using AI bot with reference image");
      console.log("Bot ID:", BOTS_IDS.STORY_IMAGE_AI);
      console.log("Bot Version:", botVersion);
      console.log("Prompt to use:", promptToUse);
      console.log("Reference image URL:", referenceImageUrl);
      
      const result = await OpenAIClient.generateWithBot(
        BOTS_IDS.STORY_IMAGE_AI,
        botVersion,
        promptToUse,
        referenceImageUrl
      );
      console.log("Result from AI bot:", result);
      
      // AI bot returns the image URL directly
      imageUrl = result;
      console.log("Story image generated by AI bot");
    } else {
      // Use the AI bot for story image generation
      const promptToUse = prompt || "create";
      console.log("Using AI bot for story image generation");
      console.log("Bot ID:", BOTS_IDS.STORY_IMAGE_AI);
      console.log("Bot Version:", botVersion);
      console.log("Prompt to use:", promptToUse);
      
      const result = await OpenAIClient.generateWithBot(
        BOTS_IDS.STORY_IMAGE_AI,
        botVersion,
        promptToUse
      );
      console.log("Result from AI bot:", result);
      
      // AI bot returns the image URL directly
      imageUrl = result;
      console.log("Story image generated by AI bot");
    }
    
    // Upload to Firebase Storage
    try {
      const uploadResponse = await fetch(`${request.nextUrl.origin}/api/ai-bots/upload-image`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          imageUrl,
          folderPath: `story-images/${additionalParams?.userId || 'anonymous'}/${additionalParams?.kidId || 'unknown'}`
        })
      });

      if (uploadResponse.ok) {
        const uploadResult = await uploadResponse.json();
        console.log('[Story Image API] Successfully uploaded to Firebase Storage');
        return { imageUrl: uploadResult.imageUrl };
      } else {
        console.warn('[Story Image API] Failed to upload to Firebase, using original URL');
        return { imageUrl };
      }
    } catch (uploadError) {
      console.warn('[Story Image API] Upload error, using original URL:', uploadError);
      return { imageUrl };
    }
  }, "Failed to generate story image").then(result => {
    if (result.success) {
      return NextResponse.json(result);
    } else {
      return NextResponse.json(result, { status: 500 });
    }
  });
}
