import { NextRequest, NextResponse } from "next/server";
import { OpenAIClient } from "@/app/network/ai-bots/OpenAIClient";
import { ResponseHandler } from "@/app/network/ai-bots/ResponseHandler";
import { BOTS_IDS, BOTS_VERSIONS } from "@/app/network/ai-bots";

export async function POST(request: NextRequest) {
  const { prompt, kidImageUrl, additionalParams } = await request.json();
  
  console.log("=== AVATAR API REQUEST ===");
  console.log("Request body:", { prompt, kidImageUrl, additionalParams });
  console.log("Prompt value:", prompt);
  console.log("KidImageUrl value:", kidImageUrl);
  
  if (!prompt && !kidImageUrl) {
    return NextResponse.json(
      ResponseHandler.error("Either a prompt or kid image is required"),
      { status: 400 }
    );
  }

  return ResponseHandler.wrap(async () => {
    let imageUrl: string;
    
    if (kidImageUrl) {
      // Use the AI bot with reference image
      const promptToUse = prompt || "create";
      console.log("Using AI bot with reference image");
      console.log("Bot ID:", BOTS_IDS.AVATAR_IMAGE_AI);
      console.log("Bot Version:", BOTS_VERSIONS.AVATAR_IMAGE_AI);
      console.log("Prompt to use:", promptToUse);
      console.log("Reference image URL:", kidImageUrl);
      
      const result = await OpenAIClient.generateWithBot(
        BOTS_IDS.AVATAR_IMAGE_AI,
        BOTS_VERSIONS.AVATAR_IMAGE_AI,
        promptToUse,
        kidImageUrl
      );
      console.log("Result from AI bot:", result);
      
      // AI bot returns the image URL directly
      imageUrl = result;
      console.log("Avatar generated by AI bot");
    } else {
      // Use the AI bot for avatar generation
      const promptToUse = prompt || "create";
      console.log("Using AI bot for avatar generation");
      console.log("Bot ID:", BOTS_IDS.AVATAR_IMAGE_AI);
      console.log("Bot Version:", BOTS_VERSIONS.AVATAR_IMAGE_AI);
      console.log("Prompt to use:", promptToUse);
      
      const result = await OpenAIClient.generateWithBot(
        BOTS_IDS.AVATAR_IMAGE_AI,
        BOTS_VERSIONS.AVATAR_IMAGE_AI,
        promptToUse
      );
      console.log("Result from AI bot:", result);
      
      // AI bot returns the image URL directly
      imageUrl = result;
      console.log("Avatar generated by AI bot");
    }
    
    // Upload to Firebase Storage
    try {
      const uploadResponse = await fetch(`${request.nextUrl.origin}/api/ai-bots/upload-image`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          imageUrl,
          folderPath: `avatars/${additionalParams?.userId || 'anonymous'}/${additionalParams?.kidId || 'unknown'}`
        })
      });

      if (uploadResponse.ok) {
        const uploadResult = await uploadResponse.json();
        console.log('[Avatar API] Successfully uploaded to Firebase Storage');
        return { imageUrl: uploadResult.imageUrl };
      } else {
        console.warn('[Avatar API] Failed to upload to Firebase, using original URL');
        return { imageUrl };
      }
    } catch (uploadError) {
      console.warn('[Avatar API] Upload error, using original URL:', uploadError);
      return { imageUrl };
    }
  }, "Failed to generate avatar").then(result => {
    if (result.success) {
      return NextResponse.json(result);
    } else {
      return NextResponse.json(result, { status: 500 });
    }
  });
}
